version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout:
          path: /app/web
      - setup_remote_docker
      - run:
          name: Get Dependencies
          command: git clone https://github.com/patrick-huber-pivotal/dependency dependencies/dependency
      - run: 
          name: Build my dockerfile
          command: |
            docker build -f /app/web/Dockerfile
